### ISSUE TITLE
Theme not working under Fedora 24 with Xfce and SDDM

### ISSUE THREAD

**Issue by marosseleng** [Match-Yang/sddm-deepin#1]
Hi, I really like your theme, but I am not able to see the theme in sddm at all. 
I tried to run your script to install the theme, but it did not work. After that I tried to copy the theme directory manually and change the `sddm.conf` but that did not work at all. 
I am kinda newbie to sddm so I have no idea why this is happenning. I can tell that the `breeze` theme is behaving in the same way, eg. when my system boots up, instead of some login UI, only white screen is shown. 
Do you have any idea? If you don't, feel free to close the issue.
Thanks

**Comment by Match-Yang** [comment]
Hi, I think you was not install all dependents packages that this theme need and cause the white screen,please run : 
`sddm-greeter --test --theme deepin/`
and check the output

**Comment by marosseleng** [comment]
Hi, thanks for the response, it was very useful! I found out that it's the Qtgraphicaleffects what I was missing. After installing it, theme now works and it looks absolutely fabulous!

If you don't mind I close the issue now.
