### ISSUE TITLE
No user is automatically selected if the user hasn't logged in previously

### ISSUE THREAD

**Issue by UriHerrera** [Match-Yang/sddm-deepin#2]
This bug happens when the user hasn't logged in to the system at all, like for exmaple on a freshly installed system.

The password field is displayed but no username is visible, entering the password results in the user not being able to log in. It's only after the user _clicks_ on the avatar that the username is displayed and the password is accepted.

**Comment by Match-Yang** [comment]
Hi,thank for your feedback. I will fix this bug as soon as possible.^_^
